export const ADD_CITY = "ADD_CITY";
export const FETCH_CITY_LOADING = "FETCH_CITY_LOADING";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR";
export const FETCH_ITINERARY_LOADING = "FETCH_ITINERARY_LOADING";
export const FETCH_ITINERARY_SUCCESS = "FETCH_ITINERARY_SUCCESS";
export const FETCH_ITINERARY_ERROR = "FETCH_ITINERARY_ERROR";
