export const ADD_CITY = "ADD_CITY";
export const FETCH_CITY_LOADING = "FETCH_CITY_LOADING";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR";
